/**
 * @file ollamaClient.js
 * @description Legacy client class for communicating with the local Ollama API service.
 * (Note: The current architecture prefers Gemini CLI. This file is retained for
 * backward compatibility or fully local LLM scenarios.)
 */
const CONFIG = require('./config');

class OllamaClient {
    constructor() {
        this.baseUrl = CONFIG.ollama.baseUrl;
        this.model = CONFIG.ollama.model;
    }

    /**
     * @description Sends an HTTP POST request to the `/api/chat` endpoint of the
     * Ollama server running on localhost.
     *
     * @param {Array<{role: string, content: string}>} messages - Chat history to send.
     * @param {boolean} useJson - Forces the model to return only JSON (uses Ollama's native `format: "json"` support).
     * @returns {Promise<string>} - Text generated by the LLM.
     * @throws {Error} - Throws an error if the server doesn't respond or returns a non-200 code.
     */
    async chat(messages, useJson = false) {
        const url = `${this.baseUrl}${CONFIG.ollama.chatEndpoint}`;

        try {
            const response = await fetch(url, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    model: this.model,
                    messages: messages,
                    stream: false,
                    format: useJson ? 'json' : undefined,
                }),
            });

            if (!response.ok) {
                throw new Error(`Ollama HTTP error: ${response.status} ${response.statusText}`);
            }

            const data = await response.json();
            return data.message?.content || '';
        } catch (error) {
            console.error('❌ Ollama connection error:', error.message);
            throw error;
        }
    }

    /**
     * @description Tests whether the Ollama server is accessible. (Used during main gateway startup.)
     * @returns {Promise<boolean>} True if successful, false if unreachable.
     */
    async healthCheck() {
        try {
            const response = await fetch(`${this.baseUrl}/api/tags`);
            return response.ok;
        } catch {
            return false;
        }
    }
}

module.exports = OllamaClient;
